### ISSUE TITLE
Incorrect line highlighted if auto wrapping is enabled

### ISSUE THREAD

**Issue by leonklingele** [natdm/go-types-atom#5]
Steps to reproduce

1. Open a Go file
2. Add a new Atom panel (horizontal axis)
3. Make the panel with your Go file in it smaller, so the lines are auto-wrapped by Atom (requires an enabled __Soft Wrap__ in the __Editor__ settings)
4. From the Go Types sidebar, click on any type
5. An incorrect line will be highlighted

**Comment by natdm** [comment]
Looks like the line is preserved from the Go file, so if it's on like 100 from the `file.go` file, it looks for like 100 on the editor, not including soft-tabs. Good find. Looking in to it.

**Comment by natdm** [comment]
@leonklingele - if you update to the newest version, let me know if this fixes it. 

A few other things were fixed as well, having to do with styling and showing a little more information on the types (things like `type MyType` now should show `type MyType SomeType{}` where they can.

**Comment by leonklingele** [comment]
Works fine now. Thank you for this nice package! 🐳
